keys:
  - &primary age17exjmsguwk2fypyrm4ctehvq4pdqhvkphwcza597cssktqrgdvzs2aegel
  - &hshen2908 age1xtsml3g4k6vq35we5a928cpcj0895s3944qp9e4l20ks647kj5lqfaegzr
creation_rules:
  - path_regex: ^secrets/users/hshen2908/.*\.yaml$
    key_groups:
      - age: [ *primary, *hshen2908 ]
  - path_regex: ^secrets/.*\.yaml$
    key_groups:
      - age: [ *primary ]
      
